# =============================================
# Configuraci�n de Base de Datos MySQL
# =============================================
db.host=localhost
db.port=3306
db.name=crud_usuarios_y_especies
db.username=root
db.password=rootroot

# =============================================
# Configuraci�n SMTP (JavaMail)
# =============================================
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=nganaj@unicartagena.edu.co
smtp.password=ardt aase qqsr iigf
smtp.from.address=nganaj@unicartagena.edu.co
smtp.from.name=Gestion de Usuarios

